version: '3.8'

services:

    #redis: Third party open source redis db
    redis:
        image: redis:latest
        hostname: redis
        ports:
            - 6379:6379
        volumes:
            - redis-data:/data
        networks:
            - demo-tester-spring-files

    #redisCommander: Third party open source gui for redis db
    redis-commander:
        image: rediscommander/redis-commander:latest
        hostname: rediscommander
        environment:
            - REDIS_HOSTS=local:redis:6379
            - HTTP_USER=admin
            - HTTP_PASSWORD=pass
        ports:
            - 8081:8081
        depends_on:
            - redis
        networks:
            - demo-tester-spring-files

    demospringfilesbackend:
        image: orbartal/demo-spring-files-backend:latest
        hostname: demospringfilesbackend
        container_name: demospringfilesbackend
        restart: always
        networks:
            - demo-tester-spring-files
        ports:
            - 8080:8080
        environment:
            - FILE_METADATA_SERVICE=redis 
            - FILE_STORAGE_SERVICE=redis
            - FILE_STORAGE_TEMP_DIR=\temp\demo
            - SPRING_REDIS_HOST=redis
            - SPRING_REDIS_PORT=6379

    demospringfilestester:
        image: orbartal/demo-spring-files-tester:latest
        hostname: demospringmongotester
        container_name: demospringmongotester
        restart: always
        networks:
            - demo-tester-spring-files
        ports:
            - 8090:8090
        depends_on:
            - demospringfilesbackend
        environment:
            - TARGET_BASE_URL=http://demospringfilesbackend:8080

networks:
    demo-tester-spring-files:

volumes:
  redis-data: